services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=coffeeshop'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  spring_app:
    image: 'dang089/coffeeshop:latest'
    ports:
      - '8080:8080'
    depends_on:
      - postgres